/*
MySQL Data Transfer
Source Host: localhost
Source Database: mangos
Target Host: localhost
Target Database: mangos
Date: 31.05.2009 23:46:12
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for db_script_string
-- ----------------------------
DROP TABLE IF EXISTS `db_script_string`;
CREATE TABLE `db_script_string` (
  `entry` int(11) unsigned NOT NULL DEFAULT '0',
  `content_default` text NOT NULL,
  `content_loc1` text,
  `content_loc2` text,
  `content_loc3` text,
  `content_loc4` text,
  `content_loc5` text,
  `content_loc6` text,
  `content_loc7` text,
  `content_loc8` text,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `db_script_string` VALUES ('2000000005', 'Hmm. It is not here. Maybe Hollee has it.......', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000004', 'It is not here too. Strange...... Where it is?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000003', 'It is Hollee\'s tent, but where Hollee?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000002', 'It is not here! hmmm....', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000001', 'Let\'s go.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000007', 'I can make it the rest of the way. $N. THANKS!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000006', 'Ok, let\'s go!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000011', 'Ok, $N. Now i can go the the Auberdine alone. Go to Terenthis. He waits for you. Thanks for the help.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000010', 'Oh, hello Grimclaw.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000009', 'Oh no! They a here!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000008', 'All right, let\'s go.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000012', 'Ok, goodluck friend. Thanks for the help.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000013', 'Until we meet again, brave one.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000014', 'Follow me.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000015', 'Whoops!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000016', 'I need to consult Noram and Horatio.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000017', 'That\'s interesting...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000018', 'Be patient $N. The torch is almost complete.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000019', 'It is done...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000020', 'come on hurry up my friend.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000024', '$N versus the ferocious clefthoof.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000023', 'The battle is about to begin!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000022', 'Get in the Ring of Blood, $N. The fight is about to start!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000026', 'Good luck stranger, and welcome to Shattrath City.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000025', '...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000029', 'And even more!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000028', 'Look out! More are coming!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000027', 'Look! Minions of Terokk are approaching!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000030', 'An Avatar of Terokk! To arms!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000033', 'Thanks again.Sergeant Doryn will be glad to hear he has one less scout to replace this week.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000034', 'You are Dismissed, $N.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000035', 'This shouldn\'t take long...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000036', 'The invisibility liquor is ready for you, $N.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000037', 'Hey there, Belm! Give me a mug of Thunder Ale, and one for my good friend $N.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000038', 'Ribbit! No!! This cannot...ribbit...be! You have duped me with...ribbit...your foul trickery! Ribbit!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000039', 'We will suffer no demon\'s servant in our lands!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000040', 'By the stars! A spirit has been summoned!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000041', 'It\'s a mystery of the past indeed! But a key to our future!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000042', 'Now let us place this rare earth in my planter...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000043', 'Thank you again, $N. This rare earth will be very helpful in my experiments.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000044', 'Peace and patience be with you, $N. Remain strong always.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000046', 'Oooooo hot hot hot! If that won\'t put spring in your step, I don\'t know what will!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000045', 'There\'s nothing like some scalding mornbrew on a chilly Dun Morogh day to get things started right!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000048', 'Thank you great spirit. Thank you!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000047', 'Spirits of Water, I give you praise, and I beg of you a favour. You have heard $N\'s pleas, and I trust his inent is noble. Please, will you aid us?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000051', 'Silence, servant! Vengeance will be mine! Death to Stormwind! Death by chicken!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000049', 'Stand back! Stand clear! The infernal will need to be given a wide berth!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000050', 'BOW DOWN TO THE ALMIGHTY! BOW DOWN BEFORE MY INFERNAL DESTRO... chicken?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000052', 'Follow me, good $C. I\'ll have your barding done faster than I could down a Dwarven stout. Mmmm... stout.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000053', 'Well, that should do it. Come now, back to the shop to finish our business!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000054', 'How many more of you grunts do I need to send back to mommy and daddy in a body bag before you grow a brain and realize that runnin\' head first into a Legion kill squad is suicide? And don\'t nod your thick skulls at me as if you know what I\'m talkin\' about!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000055', 'The threat be over! $N be savin\' us all!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000848', 'How predictable! But then, who would expect a rock to think like anything other than one?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005000', 'Fizzles used to be a great wizard. But got turned into a rabbit when one of his spells went bad.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005001', 'Hello, Charys. I have my list, could you get me all of that, especially the last ingredient.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005002', 'Sure Paige. Just be gentle.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005003', 'Thanks, Charys. C\'mon Paige, sweetie.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005004', 'Mommy? Can I pet Fizzles?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005005', 'I can\'t believe dad won\'t let me keep your sister.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005006', 'Kitten for sale, looking for a good home.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005007', 'Can anyone give my adorable, extra little kitty a home?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005008', 'What does allergic mean anyway? And what does it have to do with either of my kitties?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005009', 'Will someone please give my little kitten a good home?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005010', 'Don\'t worry, I\'ll find a good home for ya.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005011', 'Jack and Jill my wrinkled patoot! I do all the water luggin round here.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005012', 'Where\'s the water Emma? Get the water Emma? Ifn it werent fer me that lot wouldn\'t know what water looks like.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005013', 'Of course Im talking to myself. Only way to get a decent conversation in this city.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005014', 'Seems like a hundred times a day I walk all the way to get more water. No respect for their elders I tell ya.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005015', 'Deja vu. For a moment I thought I was back home... before the plague...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005016', 'Come here Fluffy!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005017', 'Please Keep Darnassus Clean.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005018', 'Litter Bugs pay a stiff fine.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005019', 'Recycle to keep Mother Earth clean.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005020', 'Poor Dorius. If I ever get my hands on those Dark Irons, so help me...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005021', 'I WIN!!!!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005022', 'Dang it!!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005023', 'ANYONE DARE CHALLENGE ME!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005024', 'YA BUNCH OF COWARDS!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005025', 'NO RISING WARRIORS IN THIS GROUP!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005026', 'Welcome to Shattrath City.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005027', 'You Seek Guidance?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005028', 'Who Dares Bother ME...I will have your Head.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005029', 'Welcome to our fair city!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005030', 'Please help keep our city clean..', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005031', 'Aye, that\'ll do it! They\'ll come runnin\' once they see the reward we\'ve put up!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005032', 'I FEEL DEATH ALONGSIDE!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005033', 'FEEL MY POWER!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005034', 'NEXT TIME YOU WILL DIE!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005035', 'YOU PRAY SERVANTS MY!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005036', 'TRY TO KILL ME LOLS!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005037', 'US ALREADY ALL ANYMORE AND ANYMORE!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005038', 'Trainees! Keep practicing your Kick Procedure. It will be very useful to you in the cruel world outside these walls.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005039', 'Heavy work this is...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005040', 'I AM A GOD OF DEMONS!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005041', 'I WILL TAKE ALL LIFES!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005042', 'I WILL DESTROY YOU ALL!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005043', 'WHERE MY FORCES OF DEMONS!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005044', 'NOBODY WILL GET THROUGH ME!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005045', 'I FEEL THE FRIED MEAT!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005046', 'I WILL DESTROY YOU ALL!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005047', 'YOU PRAY SERVANTS MY!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005048', 'NOBODY WILL GET THROUGH ME!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005049', 'I WILL DESTROY ALL!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005050', 'I WICKED OGRE!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005051', 'I FEEL DEATH ALONGSIDE!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005052', 'US ALREADY ALL ANYMORE AND ANYMORE!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005053', 'I FEEL DEATH ALONGSIDE!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005054', 'There have been some complaints filed against this... Individual. I\'m told he\'s something of a shady character. I am here to determine whether or not this business of his is legitimate... and take action if it proves otherwise.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005055', 'Welcome to Shattrath City.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005056', 'You Seek Guidance?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005057', 'I need to get this right, So watch your self !!!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005058', 'No One May Pass!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005059', 'I need to get this right, So watch your self !!!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005060', 'I need to get this right, So watch your self !!!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005061', 'Troops! Fall out!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005062', 'The techniques he has suggested have been most effective in preparing the troops.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005063', 'By your leave, High Exarch, I must prepare the next troops for your review.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005064', 'Your training is now complete. You each have your assignments. May the Light guide you.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005065', 'Listen up Men!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005066', 'I need to get this right, So watch your self !!!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005067', 'Brashly you have attacked my children, Illidan!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005068', 'The pact is broken. Giant will never side with elf! NEVER!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005069', 'Behemothon, King of the Colossi roars in defiance.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005070', 'I need to get this right, So watch your self !!!!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005071', 'Practice makes Perfect!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005072', 'Skarr the Unbreakable is in the arena! The Unbreakable is here now !', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005073', 'Fight with Skarr !', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005074', 'You will die or you will have tried ...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005075', 'Mushgog is in the arena! Mushgog is here now !', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005076', 'Fight with Mushgog ! ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005077', 'You will die or you will have tried ...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005078', 'Razza is in the arena! Razza is here now !', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005079', 'Fight with Razza !', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005080', 'You will die or you will have tried ...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005081', 'Half Done!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005082', 'Almost done with this side.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005083', 'They sure screwed up this bridge..', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005084', 'Daniel is a good worker!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005085', 'Man! I will never beat him.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005086', 'Great Work!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005087', 'Your doing great!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005088', 'Ahh, my precious Ameenah! How wonderful to see you again.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005089', 'Yer wearin down, princess, I can sense it!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005090', 'Hmm, don\'t mind if I do!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005091', 'Beat it, Mack! Else I\'ll have Budd cook ya fer my hounds...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005092', 'I\'ll never stop. Never...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005093', 'It\'s getting away!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005094', 'Hey, someone help me catch this thing!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005096', 'As if I dont have better things to do in my old age than carry buckets of water.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000715', 'don\'t let them catch me!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000718', 'let\'s take a break...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000719', 'Go on now please! and stay close to me', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000720', 'Thank you very much!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000723', 'It borders on sacrilege that these secrets be revealed to a mortal such as yourself, but I have little choice.\r\n\r\nEver since Freya, daughter of the titans, left me here I\'ve had but one task and I cannot fail. Life must be protected at any cost.\r\n\r\nThere is a waygate that links this place with another very much like this one. It is there that the weapon we seek can be found.\r\n\r\nI will not fail.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000721', 'The Scourge are a blemish upon these pristine lands. By the might of my creators, I will crush every last one of their decrepit bones under my heel.\r\n\r\nI want to stop the Scourge as much as you do. How can I help?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000722', 'The titans did not create life overnight. The process was gradual and required a great deal of experimentation and iteration.\r\n\r\nIt is for that reason that highly protected places such as Sholazar Basin exist.\r\n\r\nTo ensure the safety of their experimentation sites, the titans created a defense mechanism. Its destructive force is unparalleled however, and I will reveal no more unless you swear your fealty to my cause.\r\n\r\nYou can trust me. I am no friend of the Lich King\'s.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000724', 'don\'t panic - yes u will get quest credit for quest but come closer to me and move a bit - sry for temp workaround and not yet working spell', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000725', 'Come to finish the job, have you?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000726', 'You\'ll look me in the eyes when...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000727', '$N ?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000728', '$N I\'d recognize those horns anywhere... What have they done to you $N ?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000729', 'You don\'t remember me, do you? Blasted Scourge... They\'ve tried to drain you of everything that made you a righteous force of reckoning. \r\n\r\n Every last ounce of good... Everything that made you a tauren!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000730', 'Think $N Think back. Try and remember the rolling plains of Mulgore, where you were born. Remember the splendor of life $Gbrother:sister; \r\n\r\n You were a champion of the tauren once! This isn\'t you.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000731', 'Listen to me $N. You must fight against the Lick King\'s control. He is a monster that wants to see this world - our world - in ruin. \r\n\r\n Don\'t let him use you to accomplish his goals. You were once a hero and you can be again. \r\n\r\n Fight, damn you! Fight his control!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000732', 'There... There\'s no more time for me. I\'m done for. Finish me off $N. Do it or they\'ll kill us both $N ... Remember Mulgore. This world is worth saving.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000733', 'Do it $N! Put me out of my misery!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000734', 'I\'d like to stand for.....', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000735', '$N I\'d recognize that face anywhere.... What..... What have they done to you ?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000736', 'You don\'t remember me, do you? Blasted Scourge.... They\'ve tried to drain you of everything that made you a righteous force of reckoning. \r\n\r\n Every last ounce of good... Everything that made you a human!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000737', 'Think $N Think back. Try and remember the hills and valleys of Elwynn, where you were born. Remember the splendor of life $Gbrother:sister; \r\n\r\n You were a champion of the Alliance once! This isn\'t you.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000738', 'There... There\'s no more time for me. I\'m done for. Finish me off $N. Do it or they\'ll kill us both $N ... Remember Elwynn. This world is worth saving...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000739', 'You don\'t remember me? when you were a child your mother would leave you in my care while she served at the Temple of the Moon. \r\n\r\n I held you in my arms an fed you with honey and sheep\'s milk to calm you until she would return. You were my little angel. Blasted Scourge... What have they done to you, $N? ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000740', 'You must remember the splendor of life, brother. You were a champion of the Kaldorei once! This isn\'t you!  ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000741', 'There... There\'s no more time for me. I\'m done for. Finish me off, $N. Do it or they\'ll kill us both. $N ... Remember Teldrassil, our beloved home. This world is worth saving. ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000742', '$N I\'d recognize that face anywhere.... What..... What have they done to ye, lad ?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000743', 'You don\'t remember me, do ye? Blasted Scourge... They\'ve tried to drain ye o\' everything that made ye a righteous force o\' reckoning. \r\n\r\n  Every last ounce o\' good...Everything that made ye a son o\' Ironforge!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000744', 'Think, $N. Think back. Try and remember the snow capped mountains o\' Dun Morogh! Ye were born there, lad. Remember the splendor o\' life, $N ! \r\n\r\n  Ye were a champion o\' the dwarves once! This isn\'t ye!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000745', 'Listen to me, $N . Ye must fight against the Lich King\'s control. He\'s a monster that wants to see this world - our world - in ruin. \r\n\r\n Don\'t let him use ye\' to accomplish his goals. Ye were once a hero and ye can be again. \r\n\r\n Fight, damn ye! Fight his control!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000746', 'There... There\'s no more time for me. I\'m done for. Finish me off $N. Do it or they\'ll kill us both $N ... For KHAAAAAAAZZZ MODAAAAAANNNNNN!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000747', 'If you\'d allow me just one... ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000748', 'You don\'t remember me, do you? Blasted Scourge.... They\'ve tried to drain you of everything that made you  a pint-sized force of reckoning. \r\n\r\n Every last ounce of good... Everything that made you a gnome!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000749', 'Think $N Think back. Try and remember Gnomeregan before those damned troggs! Remember the feel of an [arclight spanner] $Gbrother:sister; \r\n\r\n You were a champion of gnome-kind once! This isn\'t you.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000750', 'There... There\'s no more time for me. I\'m done for. Finish me off, $N. Do it or they\'ll kill us both. $N ... Remember Gnomeregan! This world is worth saving. ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000751', '$N, I\'d recognize those face tentacles anywhere... What... What have they done to you, $N ? ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000752', 'You don\'t remember me, do you? Blasted Scourge... They\'ve tried to drain you of everything that made you a righteous force of reckoning. \r\n\r\n Every last ounce of good... Everything that made you a Draenei !', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000753', 'Think $N Think back. Try and remember the proud mountains of Argus, where you were born. Remember the splendor of life, $Gbrother:sister; \r\n\r\n . You were a champion of the draenei once! This isn\'t you. ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000754', 'There... There\'s no more time for me. I\'m done for. Finish me off, $N. Do it or they\'ll kill us both. $N ... Remember Argus. Don\'t let that happen to this world. ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000755', 'You don\'t remember me, do you? Blasted Scourge.... They\'ve tried to drain you of everything that made you a righteous force of reckoning. \r\n\r\n Every last ounce of good... Everything that made you a Blood Elve!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000756', 'Think $N Think back. Try and remember the majestic halls of Silvermoon City, where you were born. Remember the splendor of life, $Gbrother:sister; \r\n\r\n . You were a champion of the sin\'dorei once! This isn\'t you. ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000757', 'There... There\'s no more time for me. I\'m done for. Finish me off, $N. Do it or they\'ll kill us both. $N ... Remember Silvermoon. This world is worth saving! ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000758', 'I want to die like an orc...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000759', 'You don\'t remember me, do you? Blasted Scourge... They\'ve tried to drain you of everything that made you a righteous force of reckoning. \r\n\r\n Every last ounce of good... Everything that made you an orc!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000760', 'Think $N Think back. Try and remember the proud mountains of Durotar, where you were born. Remember the splendor of life, $Gbrother:sister; \r\n\r\n . You were a champion of the orc once! This isn\'t you. ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000761', 'There... There\'s no more time for me. I\'m done for. Finish me off, $N. Do it or they\'ll kill us both. $N ... For the Horde! This world is worth saving.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000762', 'Come ta finish da job, mon? ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000763', 'Dis troll gonna stand for da... ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000764', '$N ? Mon? ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000765', '$N I\'d recognize dem tusks anywhere... What... What have dey done ta you, mon? ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000766', 'You don\'t remember me, mon? Damn da Scourge! Dey gone ta drain you of everytin dat made ya a mojo masta. Every last ounce of good... Everytin\' dat made ya a troll hero, mon!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000767', 'TINK $N. Tink back, mon! We be Darkspear, mon! Bruddas and sistas! Remember when we fought the Zalazane and done took he head and freed da Echo Isles? \r\n\r\n MON! TINK! You was a champion of da Darkspear trolls!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000768', 'Listen ta me, $Gbrudda:sista; . You must fight against da Lich King\'s control. He be a monstar dat want ta see dis world - our world - be ruined. \r\n\r\n Don\'t let he use you ta accomplish he goals. \r\n\r\n You be a hero once and you be a hero again! Fight it, mon! Fight he control!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000769', 'Der... Der\'s no more time for me. I be done for. Finish me off $N. Do it or they\'ll kill us both. $N... Remember Sen\'jin Village, mon! Dis world be worth saving!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000770', 'Do it $N! Put out me of da misery!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000771', 'Ironic, isn\'t it? To be killed... ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000772', '$N , I\'d recognize that decay anywhere... What... What have they done to you, $N ? ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000773', 'You don\'t remember me, do you? We were humans once - long, long ago - until Lordaeron fell to the Scourge. \r\n\r\n  Your transformation to a Scourge zombie came shortly after my own. \r\n\r\n  Not long after that, our minds were freed by the Dark Lady. ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000774', 'A pact was made, $Gbrother:sister; ! We vowed vengeance against the Lich King! \r\n\r\n For what he had done to us! \r\n\r\n We battled the Scourge as Forsaken, pushing them back into the plaguelands and freeing Tirisfal! \r\n\r\n  You and I were champions of the Forsaken! ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000775', 'There... There\'s no more time for me. I\'m done for. Finish me off, $N. Do it or they\'ll kill us both. $N ... Remember Tirisfal! This world is worth saving! ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000776', 'oO oO I think i feel baaad....', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000777', 'Thank you very much ...but oO oO ...baaad', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000778', 'A-Me ACTIVATION', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000779', 'A-Me m-i-s-s-i-o-n ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000780', 'A-Me ha-ppy u-u-u-i-i-k', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000781', 'Sit and listen to my story, undead. $C \r\n\r\n >>I am ready to hear your tale, Tirion.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000782', 'I must apologize for not being entirely truthful with you in regards to my identity. \r\n\r\n I had to be certain that you could be trusted - few people would have selflessly lent assistance to an old and forgotten hermit. ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000783', 'You have proven yourself as one of those people: A person of integrity and honor. \r\n\r\n  >>Thank you, Tirion.  What of your identity?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000784', 'My son, Taelan, was only a child when I was found guilty of treason and banished from the Alliance to live a life in exile.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000785', 'I chose to remain here so that I could watch over him; to somehow insure that he would group up an honorable man.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000786', 'As I had hoped, he took my place as lord of Mardenholde; but in a cruel twist of fate, joined the ranks of the Scarlet Crusade.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000787', 'He is now their Highlord, $C \r\n\r\n >>That is terrible. ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000788', 'Indeed.  The Scarlet Crusade are an aberration of the Order of the Silver Hand.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000789', 'You must believe me, $C ; Taelan is a good man.  He needs guidance.  He needs to remember... remember what it is to be noble and honorable.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000790', 'I know that in his heart, he knows what he does is wrong.  Will you help him?  Will you help him remember? \r\n\r\n >>I will, Tirion.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000791', 'Tell me about this proposal', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000792', 'You see, Thorim is not like these harpies. He\'s a worthy being of near godlike stature.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000793', 'He served the titans as guardian of Ulduar and the Terrace of the Makers.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000794', 'That is until his wife, Sif, was cowardly slain by his brother.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000795', 'What happened then?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000796', 'Thorim lost it. He lasted out against his most beloved allies, the frost giants.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000797', 'That\'s one reason why to this day, this land is torn apart by the war between the Hyldnir and the Sons of Hodir... and why Thorim has exiled himself to the Temple of Storms.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000798', 'You want me to take part in the Hyldsmeet to end the war?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000799', 'What do I care if these she-wolves and the frost giants kill each other every day?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000800', 'No, no... I want THorim to break out of his stupor and rally all his allies to retake Ulduar.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000801', 'The world will be torn asunder if he fails to accomplish this!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000802', 'And of course, I\'ll reward you appropriately.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000803', 'Very well. I\'ll take part in this competition.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000804', 'Thorim! Come show yourself!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000805', 'The deeds of your race servant defy her stature, Stormlord. Her efforts have succeeded in softening the hearts of my people.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000806', 'Thorim says:Jokkum, son of Arngrim, I have always regretted my actions here. In my grief, I have brought great harm to those closest to me. I would ask your forgiveness for the suffering I have caused you and your people.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000807', 'Never have such humble words come from mighty Thorim. I shall deliver your words to Dun Nifflelem. The events of that dark day are hereby forgiven by my people. They shall never again be spoken of. To signify our reforged relationship, I have something which belongs to you...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000808', 'As the great explosion filled the region, my father cast a rune at the great hammer that it might not be had by our enemies. It was his final act...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000809', 'Thorim says:Krolmir... I thank you Jokkum. I hadn\'t dared hope it still existed. It shall soon see glorious battle once again!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000810', 'We welcome the opportunity to fight by your side, mighty Thorim. I must return to Dun Niffilem. We shall speak again soon, Stormlord.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000811', 'Speak, $C ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000812', 'You: Can you tell me what became of Sif? ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000813', 'For a moment I thought you were my beloved Sif... that strand of hair... but no! It can\'t be... Sif is dead....My... my brother.... killed her! ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000814', 'You: He did more than that, Thorim. He controls Ulduar now.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000815', 'Ulduar... I was sworn to protect Ulduar. \r\n\r\n Sworn to protect the Terrace of the Makers. \r\n\r\n Sworn to protect the pacts between the races of frost. \r\n\r\n But I failed! I let my brother trick me. I let him turn me against my allies. He tricked me into blaming Sif\'s death on a dear friend, Arngrim, the king of the frost giants.  \r\n\r\n After I realized what I\'d done... I... gave in to despair.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000816', 'You: It needn\'t end this way.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000817', 'Who are you, little one? To come speak these words to the mighty Thorim... \r\n\r\n I should... crush you! \r\n\r\n Yet, you\'ve delivered me from my stupor. Your presence here is a sign! \r\n\r\n It was no accident that I mistook you for Sif. What would she think of me? I must prepare for battle. \r\n\r\n I must avenge her death and liberate the titan\'s sacred grounds from my brother\'s madness! ', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000818', '*Hmm, it appears that Lok\'lira the Crone may be more than she appears. \r\n\r\n Maybe him confusing you for Sif was mere illusion on her part, but maybe it was not.*', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000819', 'Uhnhh.... It is too late for me, $Gsister:brother; \r\n\r\n I am... finished...  \r\n\r\n Stay with me, friend. I must know what happened here.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000820', 'We attacked under cover of a blizzard....  \r\n\r\n The Scourge were caught off guard... our victory was certain....  \r\n\r\n  Then... from behind us... the Horde came from nowhere.  \r\n\r\n They cost us... everything....', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000821', 'Uhnhh... Don\'t.... bother with me.\r\n\r\n I am... finished...  \r\n\r\n Hold on friend. Tell me what happened here.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000822', 'Gathering... information.... on the Scourge.  \r\n\r\n Alliance forces appeared... \r\n\r\n  We took cover - waited until they attacked the gate, then, we hit them from the rear.  \r\n\r\n Pinched between us... and the Scourge... it was too much for them...', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000823', 'AMBUSH ! We\'re under attack !', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000824', 'Don\'t forget to buy refreshments and souvenirs!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000825', 'I\'ve got my hands full here at the moment, $C. \r\n\r\n What can I do for you?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000826', 'Tell me what\'s going on out here, Fizzcrank.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000827', 'Fine then, have a seat. This might take a while. \r\n\r\n When we first came down to this frozen hell, General Arlos, down in Valiance Keep, gave my group of flying daredevils and I a special task: to establish a forward base for Alliance operations. \r\n\r\n This airstrip is the result. Let me tell you, it wasn\'t easy, what with all the nasty beasts and the ground rock-hard from being frozen. But we managed, and we did it quickly too!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000828', 'Anyway, we needed to pump up lots of sand and oil for the machinery. The nearby pools proved to be perfect for that. \r\n\r\n Some of the sand even proved to have magical properties... can you say possibilities! But that\'s a different tale. \r\n\r\n So, we drained most of the water out and built the pumping station smack dab in the middle. Everything was going swimmingly until one day the main suction pipe got clogged.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000829', 'Mind you, this part I learned later because I wasn\'t out there at the time. \r\n\r\n When they ratched up the suction on the pump, up came pieces of a robot that looked like a gnome! Of course the fools worked night and day to put it back together without telling us. \r\n\r\n This is when we lost communication with the pumping station.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000830', 'After a couple days of silence, I sent a scouting party out to the platform. They never returned. \r\n\r\n I sent another group the next day with the same results, and lost a couple of flying machines out on aerial recon. \r\n\r\n At that point I sent someone south to find help, and we hunkered down to prepare for the worst. We turned all of our attention to making armor, weapons and robots so that we could head out there in full force. \r\n\r\n When we did a few days ago, we couldn\'t believe our eyes!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000831', 'As I was saying, what we saw out there defied explanation. \r\n\r\n my people were nowhere to be found, but in their place was a veritable army of robots and androids going about their business! \r\n\r\n The droids all looked like gnomes and they said that they\'d been expecting us. In fact, in their own strange way, they acted like they knew us. We were surrounded and quickly taken to the top of the pumping station. \r\n\r\n That\'s where we saw their leader and what he was doing to the surviving gnomes!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000832', 'He called himself Gearmaster Mechazod. When we arrived he was busy transforming the survivors into mechanical beings! \r\n\r\n He greeted us warmly and explained that he was one of the first gnomes ever to be created by something he called \"The Grand Architect\", a Titan keeper from within the halls of fabled Ulduar. \r\n\r\n Apparently he was the blockage that my team had accidentally sucked up from where he\'d malfunctioned thousands of years ago. It was just our luck that we\'d built the pumping station right above him.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000833', 'The station\'s mechanics had put him back together, bringing him back to \"life\". \r\n\r\n And now, by way of thanks, he was going to return the favor by curing all of us of what he called the \"Curse of the Flesh\". \r\n\r\n According to Mechazod, it\'s a condition that eventually befalls all of the creations of the Titans! In other words, we all supposedly start out as robots of some kind, and, over thousands of years, slowly turn into fleshy beings! \r\n\r\n Preposterous, I know.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000834', 'It didn\'t look like much of a \"cure\" to me, and I wasn\'t about to stand around listening to some crazy robot while he was butchering my people! \r\n\r\n We did what any sane gnome would do... we ran! Well, actually, most of us parachuted off the side of the platform, but you get the picture. \r\n\r\n Not many of us managed to make it back here, and we\'re still spread thin from having to deal with everything else too, like the magnataur to the north and the Scourge to the east. To make things worse, the Horde just set up shop to the northwest!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000835', 'And that\'s where we find ourselves now, $N. \r\n\r\n We can\'t possibly deal with all of this by ourselves, and quite frankly, I feel a little out of my depth. Jinky knows what needs to be done. You should go see her now. \r\n\r\n I just hope you\'ll be able to get us out of this mess with our bodies intact.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000841', 'You dedicated your life to fighting the Scourge. You saw what they did to our beloved Lordaeron. The Lich King took everything from you!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000839', 'LEGION, STEADY YOURSELVES!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000840', 'Honor, courage, compassion and justice! These were once the virtues you fought for as a cleric of the Argent Dawn, Thel\'zan.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000838', 'It is this phylactery Thel\'zan\'s phylactery - that is the key to victory!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000837', 'Death comes for us all eventually, but sometimes it comes a little faster than anticipated. Today we call that blind heroics... Tomorrow someone may call it stupidity.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000836', 'Steel yourselves, soldiers. $N has provided us with the final piece of this puzzle. The dread lich, Thel\'zan, will soon come out of hiding, only to be rendered powerless against us!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000846', 'No. I will leave this world in a manner of my own choosing. And I will return, the grand admiral\'s will permitting!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000844', 'There is much that you do not understand, $C. The Master sees all.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000845', 'He told me that you would come for me. I won\'t die by your hand, though. I have seen what you have done to my compatriots.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000843', 'Did you think that I could not see through your flimsy disguise, $N?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000842', 'So how, then, did Father Inigo Montoy, bastion of virtue for the Argent Dawn, become the embodiment of that which he hated most?', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000847', 'AAAEEEIIIiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiii.............................................', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005097', 'Free drinks at the Blue Recluse!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005098', 'Head on over to the Blue Recluse. Where everybody knows your name!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000005099', 'Best drinks in Stormwind!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000000849', 'If you\'re so eager to fight, I\'ll oblige you. But know that nothing you do here can prevent the completion of the iron colossus!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000001008', 'Thank you, $N.', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001009', 'I, of course, can find application of the mixture...', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001010', 'Ha! $ N, I did not move from their seats!', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001011', 'tries to open the wooden leg Maury...', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001012', 'shown on The Mind\'s Eye and Singing Crystals...', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001013', 'Soul Gems Yenniku ready, $N...', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001015', 'Blue with red ... I thought so ...', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001016', 'Here it is, $N! Finally, I understand!', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001017', 'Good luck, mighty hero. May your victories continue to bring you fame and power as you lay waste to Scholomance!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000001018', 'Welcome to the Plaguelands, hero. This is one of the most dangerous frontiers in Azeroth, with the looming threat of the Scourge to our east, and then even further still eastward from there. I am glad to hear that the call of duty and service to the Horde did not fall on deaf ears with you!', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000001021', 'Go!', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001020', 'Would never have thought that this oil will be mana! Oh, it is all you need, except the Grek, of course.', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001025', 'Remember, $N, bloodspore powder can be used to weaken all magnataurs in Gammothra.', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001024', 'Information that you\'re looking for ... I can not make them just so. Prove that we have common enemies.', null, null, null, null, null, null, null, null);
INSERT INTO `db_script_string` VALUES ('2000001022', 'No,not so.What happened here?', null, null, null, null, null, null, null, '');
INSERT INTO `db_script_string` VALUES ('2000001023', 'Metal lost its magic. I could make out his weapon, but it will not differ from the conventional blade.', null, null, null, null, null, null, null, '');
