/*
MySQL Data Transfer
Source Host: localhost
Source Database: mangos
Target Host: localhost
Target Database: mangos
Date: 31.05.2009 23:50:53
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for mangos_string
-- ----------------------------
DROP TABLE IF EXISTS `mangos_string`;
CREATE TABLE `mangos_string` (
  `entry` mediumint(8) unsigned NOT NULL DEFAULT '0',
  `content_default` text NOT NULL,
  `content_loc1` text,
  `content_loc2` text,
  `content_loc3` text,
  `content_loc4` text,
  `content_loc5` text,
  `content_loc6` text,
  `content_loc7` text,
  `content_loc8` text,
  PRIMARY KEY (`entry`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `mangos_string` VALUES ('1', 'You should select a character or a creature.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('2', 'You should select a creature.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('5', 'There is no help for that command', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('6', 'There is no such command', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('7', 'There is no such subcommand', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('8', 'Command %s have subcommands:%s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9', 'Commands available to you:', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('10', 'Incorrect syntax.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('11', 'Your account level is: %i', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('12', 'Online players: %u (max: %u) Queued players: %u (max: %u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('13', 'Server uptime: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('14', 'Player saved.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('15', 'All players saved.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('16', 'There are the following active GMs on this server:', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('17', 'There are no GMs currently logged in on this server.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('18', 'Cannot do that while flying.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('19', 'Cannot do that in Battlegrounds.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('20', 'Target is flying you can\'t do that.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('21', '%s is flying command failed.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('22', 'You are not mounted so you can\'t dismount.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('23', 'Cannot do that while fighting.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('24', 'You used it recently.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('54', 'The new passwords do not match', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('55', 'Your password can\'t be longer than 16 characters (client limit), password not changed!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('26', 'The password was changed', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('27', 'The new passwords do not match or the old password is wrong', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('28', 'Your account is now locked.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('29', 'Your account is now unlocked.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('30', ', rank ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('31', ' [known]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('3', '|cffff0000[System Message]: %s|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('4', '|cffff0000[Event Message]: %s|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('32', ' [learn]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('33', ' [passive]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('34', ' [talent]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('35', ' [active]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('36', ' [complete]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('37', ' (offline)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('38', 'on', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('39', 'off', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('40', 'You are: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('41', 'visible', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('42', 'invisible', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('43', 'done', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('44', 'You', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('45', ' <unknown> ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('46', '<error>', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('47', '<non-existing character>', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('48', 'UNKNOWN', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('49', 'You must be at least level %u to enter.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('50', 'You must be at least level %u and have item %s to enter.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('51', 'Hello! Ready for some training?', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('100', 'Global notify: ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('276', 'Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) turned', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('539', 'Player selected NPC\nGUID: %u.\nFaction: %u.\nnpcFlags: %u.\nEntry: %u.\nDisplayID: %u (Native: %u).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('102', '%s is already being teleported.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('103', 'You can summon a player to your instance only if he is in your party with you as leader.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('104', 'You cannot go to the player\'s instance because you are in a party now.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('105', 'You can go to the player\'s instance while not being in his party only if your GM mode is on.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('106', 'You can not go to player %s from instance to instance.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('107', 'You can not summon player %s from instance to instance.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('108', 'You are summoning %s%s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('109', 'You are being summoned by %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('110', 'You are teleporting %s%s to %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('111', 'You are being teleported by %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('112', 'Player (%s) does not exist.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('113', 'Appearing at %s\'s location.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('114', '%s is appearing to your location.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('115', 'Incorrect values.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('116', 'No character selected.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('117', '%s is not in a group.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('118', 'You changed HP of %s to %i/%i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('119', '%s changed your HP to %i/%i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('120', 'You changed MANA of %s to %i/%i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('121', '%s changed your MANA to %i/%i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('122', 'You changed ENERGY of %s to %i/%i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('123', '%s changed your ENERGY to %i/%i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('124', 'Current energy: %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('125', 'You changed rage of %s to %i/%i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('126', '%s changed your rage to %i/%i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('127', 'You changed level of %s to %i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('128', 'GUID %i, faction is %i, flags is %i, npcflag is %i, DY flag is %i', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('129', 'Wrong faction: %u (not found in factiontemplate.dbc).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('130', 'You changed GUID=%i \'s Faction to %i, flags to %i, npcflag to %i, dyflag to %i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('131', 'You changed the spellflatid=%i, val= %i, mark =%i to %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('132', '%s changed your spellflatid=%i, val= %i, mark =%i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('133', '%s has access to all taxi nodes now (until logout).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('134', '%s has no more access to all taxi nodes now (only visited accessible).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('135', '%s has given you access to all taxi nodes (until logout).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('136', '%s has removed access to all taxi nodes (only visited still accessible).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('137', 'You set all speeds to %2.2f from normal of %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('138', '%s set all your speeds to %2.2f from normal.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('139', 'You set the speed to %2.2f from normal of %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('140', '%s set your speed to %2.2f from normal.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('141', 'You set the swim speed to %2.2f from normal of %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('142', '%s set your swim speed to %2.2f from normal.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('143', 'You set the backwards run speed to %2.2f from normal of %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('144', '%s set your backwards run speed to %2.2f from normal.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('145', 'You set the fly speed to %2.2f from normal of %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('146', '%s set your fly speed to %2.2f from normal.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('147', 'You set the size %2.2f of %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('148', '%s set your size to %2.2f.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('149', 'There is no such mount.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('150', 'You give a mount to %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('151', '%s gave you a mount.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('423', 'IP: %s\nBan Date: %s\nUnban Date: %s\nRemaining: %s\nReason: %s\nSet by: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('153', 'You take all copper of %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('154', '%s took you all of your copper.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('155', 'You take %i copper from %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('156', '%s took %i copper from you.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('157', 'You give %i copper to %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('158', '%s gave you %i copper.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('159', 'You hear sound %u.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('161', 'Removed bit %i in field %i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('162', 'Set bit %i in field %i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('163', 'Teleport location table is empty!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('164', 'Teleport location not found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('165', 'Requires search parameter.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('166', 'There are no teleport locations matching your request.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('290', 'Ticket of %s (Last updated: %s):\n%s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('169', 'Mail sent to %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('200', 'No selection.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('201', 'Object GUID is: lowpart %u highpart %X', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('202', 'The name was too long by %i characters.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('203', 'Error, name can only contain characters A-Z and a-z.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('204', 'The subname was too long by %i characters.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('205', 'Not yet implemented', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('206', 'Item \'%i\' \'%s\' added to list with maxcount \'%i\' and incrtime \'%i\' and extendedcost \'%i\'', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('207', 'Item \'%i\' not found in database.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('208', 'Item \'%i\' \'%s\' deleted from vendor list', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('209', 'Item \'%i\' not found in vendor list.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('210', 'Item \'%i\' already in vendor list.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('211', 'Spells of %s reset.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('212', 'Spells of %s will reset at next login.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('213', 'Talents of %s reset.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('214', 'Talents of %s will reset at next login.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('215', 'Your spells have been reset.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('216', 'Your talents have been reset.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('217', 'Unknown case \'%s\' for .resetall command. Type full correct case name.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('218', 'Spells will reset for all players at login. Strongly recommend re-login!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('219', 'Talents will reset for all players at login. Strongly recommend re-login!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('220', 'Creature (GUID: %u) No waypoint found.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('221', 'Creature (GUID: %u) Last waypoint not found.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('222', 'Creature (GUID: %u) No waypoint found - used \'wpguid\'. Now trying to find it by its position...', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('223', 'Creature (GUID: %u) No waypoints found - This is a MaNGOS db problem (single float).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('224', 'Selected creature is ignored - provided GUID is used', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('225', 'Creature (GUID: %u) not found', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('226', 'You must select a visual waypoint.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('227', 'No visual waypoints found', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('228', 'Could not create visual waypoint with creatureID: %d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('229', 'All visual waypoints removed', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('230', 'Could not create waypoint-creature with ID: %d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('231', 'No GUID provided.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('232', 'No waypoint number provided.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('233', 'Argument required for \'%s\'.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('234', 'Waypoint %i added to GUID: %d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('235', 'Waypoint %d added.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('236', 'Waypoint changed.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('237', 'Waypoint %s modified.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('238', 'WP export successfull.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('239', 'No waypoints found inside the database.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('240', 'File imported.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('241', 'Waypoint removed.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('242', 'Warning: Could not delete WP from the world with ID: %d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('243', 'This happens if the waypoint is too far away from your char.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('244', 'The WP is deleted from the database, but not from the world here.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('245', 'They will disappear after a server restart.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('246', 'Waypoint %d: Info for creature: %s, GUID: %d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('247', 'Waittime: %d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('248', 'Model %d: %d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('249', 'Emote: %d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('250', 'Spell: %d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('251', 'Text%d (ID: %i): %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('252', 'AIScript: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('253', 'Forced rename for player %s will be requested at next login.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('254', 'Forced rename for player %s (GUID #%u) will be requested at next login.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('255', 'Waypoint-Creature (GUID: %u) Not found', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('256', 'Could not find NPC...', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('257', 'Creature movement type set to \'%s\', waypoints removed (if any).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('258', 'Creature movement type set to \'%s\', waypoints were not removed.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('259', 'Incorrect value, use on or off', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('260', 'Value saved.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('261', 'Value saved, you may need to rejoin or clean your client cache.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('262', 'Areatrigger ID %u not found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('263', 'Target map or coordinates is invalid (X: %f Y: %f MapId: %u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('264', 'Zone coordinates is invalid (X: %f Y: %f AreaId: %u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('265', 'Zone %u (%s) is part of instanceable map %u (%s)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('266', 'Nothing found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('267', 'Object not found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('268', 'Creature not found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('269', 'Warning: Mob found more than once - you will be teleported to the first one found in DB.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('270', 'Creature Removed', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('271', 'Creature moved.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('272', 'Creature (GUID:%u) must be on the same map as player!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('273', 'Game Object (GUID: %u) not found', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('274', 'Game Object (GUID: %u) has references in not found creature %u GO list, can\'t be deleted.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('275', 'Game Object (GUID: %u) removed', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('277', 'Game Object |cffffffff|Hgameobject:%d|h[%s]|h|r (GUID: %u) moved', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('278', 'You must select a vendor', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('279', 'You must send id for item', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('280', 'Vendor has too many items (max 128)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('281', 'You can\'t kick self, logout instead', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('282', 'Player |cffff0000%s|r kicked by |cffff0000%s|r. Reason: |cffff0000%s|r.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('171', 'You can\'t teleport self to self!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('284', 'Accepting Whisper: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('285', 'Accepting Whisper: ON', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('286', 'Accepting Whisper: OFF', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('287', 'Creature (GUID: %u) not found', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('288', 'Tickets count: %i show new tickets: %s\n', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('289', 'New ticket from %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('291', 'New ticket show: ON', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('292', 'New ticket show: OFF', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('293', 'Ticket %i doesn\'t exist', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('294', 'All tickets deleted.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('295', 'Character %s ticket deleted.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('296', 'Ticket deleted.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('297', 'Spawn distance changed to: %f', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('298', 'Spawn time changed to: %i', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('299', 'The honor of %s was set to %u!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('300', 'Your chat has been disabled for %u minutes.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('301', 'You have disabled %s\'s chat for %u minutes.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('302', 'Player\'s chat is already enabled.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('303', 'Your chat has been enabled.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('304', 'You have enabled %s\'s chat.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('400', '|cffff0000[System Message]:|rScripts reloaded', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('402', '%s changed your security level to %i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('403', 'You have low security level for this.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('404', 'Creature movement disabled.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('405', 'Creature movement enabled.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('406', 'Weather can\'t be changed for this zone.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('407', 'Weather system disabled at server.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('408', '%s is banned for %s. Reason: %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('409', '%s is banned permanently for %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('410', '%s %s not found', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('411', '%s unbanned.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('412', 'There was an error removing the ban on %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('25', 'Password not changed (unknown error)!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('414', 'There is no such character.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('415', 'There is no such IP in banlist.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('416', 'Account %s has never been banned', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('417', 'Ban history for account %s:', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('418', 'Ban Date: %s Bantime: %s Still active: %s  Reason: %s Set by: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('419', 'Inf.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('420', 'Never', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('421', 'Yes', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('422', 'No', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('160', 'USER2: %i, ADD: %i, RESULT: %i\n', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('424', 'There is no matching IPban.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('425', 'There is no matching account.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('426', 'There is no banned account owning a character matching this part.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('427', 'The following IPs match your pattern:', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('428', 'The following accounts match your query:', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('429', 'You learned many spells/skills.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('430', 'You learned all spells for class.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('431', 'You learned all talents for class.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('432', 'You learned all languages.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('433', 'You learned all craft skills and recipes.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('434', 'Could not find \'%s\'', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('435', 'Invalid item id: %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('436', 'No items found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('437', 'Invalid gameobject id: %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('438', 'Found items %u: %u ( inventory %u mail %u auction %u guild %u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('439', 'Found gameobjects %u: %u ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('440', 'Invalid creature id: %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('441', 'Found creatures %u: %u ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('442', 'No area found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('443', 'No item sets found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('444', 'No skills found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('445', 'No spells found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('446', 'No quests found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('447', 'No creatures found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('448', 'No gameobjects found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('449', 'Graveyard #%u doesn\'t exist.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('450', 'Graveyard #%u already linked to zone #%u (current).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('451', 'Graveyard #%u linked to zone #%u (current).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('452', 'Graveyard #%u can\'t be linked to subzone or not existed zone #%u (internal error).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('454', 'No faction in Graveyard with id= #%u , fix your DB', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('455', 'invalid team, please fix database', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('456', 'any', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('457', 'alliance', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('458', 'horde', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('459', 'Graveyard #%u (faction: %s) is nearest from linked to zone #%u.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('460', 'Zone #%u doesn\'t have linked graveyards.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('461', 'Zone #%u doesn\'t have linked graveyards for faction: %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('462', 'Teleport location already exists!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('463', 'Teleport location added.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('464', 'Teleport location NOT added: database error.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('465', 'Teleport location deleted.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('168', 'Locations found are:\n%s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('467', 'Target unit has %d auras:', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('469', 'Target unit has %d auras of type %d:', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('471', 'Quest %u not found.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('472', 'Quest %u started from item. For correct work, please, add item to inventory and start quest in normal way: .additem %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('473', 'Quest removed.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('474', ' [rewarded]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('475', ' [complete]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('476', ' [active]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('477', '%s\'s Fly Mode %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('478', 'Opcode %u sent to %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('479', 'Character loaded successfully!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('480', 'Failed to load the character!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('481', 'Character dumped successfully!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('482', 'Character dump failed!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('483', 'Spell %u broken and not allowed to cast or learn!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('484', 'Skill %u (%s) for player %s set to %u and current maximum set to %u (without permanent (talent) bonuses).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('485', 'Player %s must have skill %u (%s) before using this command.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('486', 'Invalid skill id (%u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('487', 'You learned default GM spells/skills.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('488', 'You already know that spell.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('489', 'Target(%s) already know that spell.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('490', '%s doesn\'t know that spell.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('491', 'You already forgot that spell.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('492', 'All spell cooldowns removed for %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('493', 'Spell %u cooldown removed for %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('494', 'Command : Additem, itemId = %i, amount = %i', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('495', 'Command : Additemset, itemsetId = %i', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('496', 'Removed itemID = %i, amount = %i from %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('497', 'Cannot create item \'%i\' (amount: %i)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('498', 'You need to provide a guild name!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('499', 'Player not found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('500', 'Player already has a guild!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('501', 'Guild not created! (already exists?)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('502', 'No items from itemset \'%u\' found.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('503', 'The distance is: (3D) %f (2D) %f yards.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('504', 'Item \'%i\' \'%s\' Item Slot %i', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('505', 'Item \'%i\' doesn\'t exist.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('506', 'Item \'%i\' \'%s\' Added to Slot %i', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('507', 'Item save failed!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('508', '%d - owner: %s (guid: %u account: %u ) %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('509', '%d - sender: %s (guid: %u account: %u ) receiver: %s (guid: %u account: %u ) %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('510', '%d - owner: %s (guid: %u account: %u ) %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('511', 'Wrong link type!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('512', '%d - |cffffffff|Hitem:%d:0:0:0:0:0:0:0|h[%s]|h|r ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('513', '%d - |cffffffff|Hquest:%d|h[%s]|h|r %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('514', '%d - |cffffffff|Hcreature_entry:%d|h[%s]|h|r ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('515', '%d - |cffffffff|Hcreature:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('516', '%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('517', '%d - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('519', '|cffffffff|Htele:%s|h[%s]|h|r ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('520', '%d - |cffffffff|Hspell:%d|h[%s]|h|r ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('518', '%d - |cffffffff|Hitemset:%d|h[%s %s]|h|r ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('522', 'Game Object (GUID: %u) not found', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('523', '>> Game Object %s (GUID: %u) at %f %f %f. Orientation %f.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('152', 'USER1: %i, ADD: %i, DIF: %i\n', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('525', '>> Add Game Object \'%i\' (%s) (GUID: %i) added at \'%f %f %f\'.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('526', '%s (lowguid: %u) movement generators stack:', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('527', '   Idle', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('528', '   Random', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('529', '   Waypoint', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('530', '   Animal random', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('531', '   Confused', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('532', '   Targeted to player %s (lowguid %u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('533', '   Targeted to creature %s (lowguid %u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('534', '   Targeted to <NULL>', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('535', '   Home movement to (X:%f Y:%f Z:%f)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('536', '   Home movement used for player?!?', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('537', '   Taxi flight', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('538', '   Unknown movement generator (%u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('540', 'Level: %u.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('541', 'Health (base): %u. (max): %u. (current): %u.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('101', 'Map: %u (%s) Zone: %u (%s) Area: %u (%s) Phase: %u\nX: %f Y: %f Z: %f Orientation: %f\ngrid[%u,%u]cell[%u,%u] InstanceID: %u\n ZoneX: %f ZoneY: %f\nGroundZ: %f FloorZ: %f Have height data (Map: %u VMap: %u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('543', 'Loot: %u Pickpocket: %u Skinning: %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('544', 'Position: %f %f %f.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('545', '*** Is a vendor!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('546', '*** Is a trainer!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('547', 'InstanceID: %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('548', 'Player%s %s (guid: %u) Account: %s (id: %u) GMLevel: %u Last IP: %s Last login: %s Latency: %ums', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('549', 'Played time: %s Level: %u Money: %ug%us%uc', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('550', 'Command .pinfo doesn\'t support \'rep\' option for offline players.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('551', '%s has explored all zones now.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('552', '%s has no more explored zones.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('553', '%s has explored all zones for you.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('554', '%s has hidden all zones from you.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('555', 'Hover enabled', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('556', 'Hover disabled', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('559', '%s reset your level progress.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('558', '%s level down you to (%i)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('557', '%s level up you to (%i)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('560', 'The area has been set as explored.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('561', 'The area has been set as not explored.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('562', 'GUID=%i \'s updateIndex: %i, value:  %i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('563', 'You change GUID=%i \'s UpdateIndex: %i value to %i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('564', 'The value index %u is too big to %u(count: %u).', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('565', 'Set %u uint32 Value:[OPCODE]:%u [VALUE]:%u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('566', 'You Set %u Field:%u to uint32 Value: %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('567', 'Set %u float Value:[OPCODE]:%u [VALUE]:%f', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('568', 'You Set %u Field:%i to float Value: %f', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('569', 'Get %u uint32 Value:[OPCODE]:%u [VALUE]:%u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('570', 'The uint32 value of %u in %u is: %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('571', 'Get %u float Value:[OPCODE]:%u [VALUE]:%f', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('572', 'The float of %u value in %u is: %f', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('573', '.Set32Bit:[OPCODE]:%u [VALUE]:%u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('574', 'You set Bit of Field:%u to Value: %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('575', '.Mod32Value:[OPCODE]:%u [VALUE]:%i', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('576', 'You modified the value of Field:%u to Value: %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('577', 'You are now invisible.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('578', 'You are now visible.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('600', 'The Alliance wins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('601', 'The Horde wins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('602', 'The battle for Warsong Gulch begins in 1 minute.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('603', 'The battle for Warsong Gulch begins in 30 seconds. Prepare yourselves!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('604', 'Let the battle for Warsong Gulch begin!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('605', '$n captured the Horde flag!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('606', '$n captured the Alliance flag!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('607', 'The Horde flag was dropped by $n!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('608', 'The Alliance Flag was dropped by $n!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('609', 'The Alliance Flag was returned to its base by $n!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('610', 'The Horde flag was returned to its base by $n!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('611', 'The Horde flag was picked up by $n!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('612', 'The Alliance Flag was picked up by $n!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('613', 'The flags are now placed at their bases.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('650', 'Alliance', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('651', 'Horde', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('652', 'stables', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('653', 'blacksmith', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('654', 'farm', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('655', 'lumber mill', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('656', 'mine', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('657', 'The %s has taken the %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('658', '$n has defended the %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('659', '$n has assaulted the %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('660', '$n claims the %s! If left unchallenged, the %s will control it in 1 minute!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('661', 'The Battle for Arathi Basin begins in 1 minute.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('662', 'The Battle for Arathi Basin begins in 30 seconds. Prepare yourselves!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('663', 'The Battle for Arathi Basin has begun!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('664', 'The Alliance has gathered $1776W resources, and is near victory!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('665', 'The Horde has gathered $1777W resources, and is near victory!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('700', 'You must be level %u to form an arena team', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('701', 'One minute until the Arena battle begins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('702', 'Thirty seconds until the Arena battle begins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('703', 'Fifteen seconds until the Arena battle begins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('704', 'The Arena battle has begun!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('705', 'You must wait %s before speaking again.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('706', 'This item(s) have problems with equipping/storing in inventory.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('542', 'Unit Flags: %u.\nDynamic Flags: %u.\nFaction Template: %u.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('579', 'Selected player or creature not have victim.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('707', '%s wishes to not be disturbed and cannot receive whisper messages: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('708', '%s is Away from Keyboard: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('709', 'Do not Disturb', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('710', 'Away from Keyboard', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('580', 'Player %s learned all default spells for race/class and completed quests rewarded spells.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('468', 'id: %d eff: %d type: %d duration: %d maxduration: %d name: %s%s%s caster: %s %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('666', 'After your recent battle in %s our best attempts to award you a Mark of Honor failed. Enclosed you will find the Mark of Honor we were not able to deliver to you at the time. Thanks for fighting in %s!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('581', 'Found near gameobjects (distance %f): %u ', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('305', 'Faction %s (%u) reputation of %s was set to %5d!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('306', 'The arena points of %s was set to %u!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('307', 'No faction found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('308', 'Faction %i unknown!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('309', 'Invalid parameter %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('310', 'delta must be between 0 and %d (inclusive)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('311', '%d - |cffffffff|Hfaction:%d|h[%s]|h|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('312', ' [visible]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('313', ' [at war]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('315', ' [hidden]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('314', ' [peace forced]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('317', ' [inactive]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('318', 'Hated', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('319', 'Hostile', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('320', 'Unfriendly', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('321', 'Neutral', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('322', 'Friendly', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('323', 'Honored', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('324', 'Revered', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('325', 'Exalted', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('326', 'Faction %s (%u) can\'not have reputation.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('327', ' [no reputation]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('582', 'SpawnTime: Full:%s Remain:%s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('680', 'The Horde has lost control of the Blood Elf Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('636', 'The Battle for Eye of the Storm begins in 1 minute.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('637', 'The Battle for Eye of the Storm begins in 30 seconds.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('638', 'The Battle for Eye of the Storm has begun!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('679', 'The Alliance has lost control of the Blood Elf Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('678', 'The Horde has lost control of the Draenei Ruins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('677', 'The Alliance has lost control of the Draenei Ruins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('676', 'The Horde has lost control of the Mage Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('675', 'The Alliance has lost control of the Mage Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('674', 'The Horde has taken control of the Fel Reaver Ruins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('673', 'The Alliance has taken control of the Fel Reaver Ruins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('672', 'The Horde has taken control of the Blood Elf Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('671', 'The Alliance has taken control of the Blood Elf Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('670', 'The Horde has taken control of the Draenei Ruins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('669', 'The Alliance has taken control of the Draenei Ruins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('668', 'The Horde has taken control of the Mage Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('667', 'The Alliance has taken control of the Mage Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('615', 'The Horde flag is now placed at its base.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('614', 'The Alliance flag is now placed at its base.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('470', 'id: %d eff: %d name: %s%s%s caster: %s %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('316', ' [invisible forced]', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('583', '%d - |cffffffff|Hgameevent:%d|h[%s]|h|r%s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('584', 'No event found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('585', 'Event not exist!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('586', 'Event %u: %s%s\nStart: %s End: %s Occurence: %s Length: %s\nNext state change: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('587', 'Event %u already active!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('588', 'Event %u not active!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('589', '   Point movement to (X:%f Y:%f Z:%f)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('590', '   Fear movement', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('591', '   Distract movement', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('592', 'You have learned all spells in craft: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('170', 'You try to hear sound %u but it doesn\'t exist.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('711', 'Queue status for %s (Lvl: %u to %u)\nQueued alliances: %u (Need at least %u more)\nQueued hordes: %u (Need at least %u more)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('712', '|cffff0000[BG Queue Announcer]:|r %s -- [%u-%u] A: %u/%u, H: %u/%u|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('328', 'Characters at account %s (Id: %u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('329', '  %s (GUID %u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('330', 'No players found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('331', 'Extended item cost %u not exist', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('332', 'GM mode is ON', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('333', 'GM mode is OFF', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('334', 'GM Chat Badge is ON', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('335', 'GM Chat Badge is OFF', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('713', 'You must be level %u to join an arena team!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('715', 'You don\'t meet Battleground level requirements', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('801', 'You do not have enough gold', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('802', 'You do not have enough free slots', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('803', 'Your partner does not have enough free bag slots', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('804', 'You do not have permission to perform that function', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('805', 'Unknown language', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('806', 'You don\'t know that language', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('807', 'Please provide character name', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('808', 'Player %s not found or offline', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('809', 'Account for character %s not found', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('52', 'Invaid item count (%u) for item %u', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('53', 'Mail can\'t have more %u item stacks', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('56', 'Current Message of the day: \r\n%s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('172', 'server console command', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('401', 'You change security level of account %s to %i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('413', 'Account not exist: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('593', 'Currently Banned Accounts:', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('594', '|    Account    |   BanDate    |   UnbanDate  |  Banned By    |   Ban Reason  |', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('595', 'Currently Banned IPs:', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('596', '|      IP       |   BanDate    |   UnbanDate  |  Banned By    |   Ban Reason  |', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('597', 'Current gamemasters:', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('598', '|    Account    |  GM  |', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('599', 'No gamemasters.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1000', 'Exiting daemon...', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1001', 'Account deleted: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1002', 'Account %s NOT deleted (probably sql file format was updated)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1003', 'Account %s NOT deleted (unknown error)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1004', 'Account created: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1005', 'Account name can\'t be longer than 16 characters (client limit), account not created!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1006', 'Account with this name already exist!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1007', 'Account %s NOT created (probably sql file format was updated)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1008', 'Account %s NOT created (unknown error)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1009', 'Player %s (Guid: %u) Account %s (Id: %u) deleted.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1010', '|    Account    |       Character      |       IP        | GM | Expansion |', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1100', 'Account %s (Id: %u) have up to %u expansion allowed now.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1101', 'Message of the day changed to:\r\n%s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1102', 'Message sent to %s: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1103', '%d - %s %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1104', '%d - %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1105', '%d - %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1106', '%d - %s %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1107', '%d - %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1108', '%d - %s %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('521', '%d - |cffffffff|Hskill:%d|h[%s %s]|h|r %s %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1110', '%d - %s X:%f Y:%f Z:%f MapId:%d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1111', '%d - %s X:%f Y:%f Z:%f MapId:%d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1112', 'Failed to open file: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1113', 'Account %s (%u) have max amount allowed characters (client limit)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1114', 'Dump file have broken data!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1115', 'Invalid character name!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1116', 'Invalid character guid!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1117', 'Character guid %u in use!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1118', '%d - guild: %s (guid: %u) %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('57', 'Using World DB: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('58', 'Using script library: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('336', 'You repair all %s\'s items.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('337', 'All your items repaired by %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('338', 'You set waterwalk mode %s for %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('339', 'Your waterwalk mode %s by %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('340', '%s is now following you.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('341', '%s is not following you.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('342', '%s is now not following you.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('343', 'Creature (Entry: %u) cannot be tamed.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('344', 'You already have pet.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1119', 'You must use male or female as gender.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1120', 'You change gender of %s to %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1121', 'Your gender changed to %s by %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('345', 'Forced customize for player %s will be requested at next login.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('346', 'Forced customize for player %s (GUID #%u) will be requested at next login.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('717', '|cffff0000[BG Queue Announcer]:|r %s -- [%u-%u] Started!|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('718', '|cffff0000[Arena Queue Announcer]:|r %s -- Joined : %ux%u : %u|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('719', '|cffff0000[Arena Queue Announcer]:|r %s -- Exited : %ux%u : %u|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('720', 'Your group is too large for this battleground. Please regroup to join.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('721', 'Your group is too large for this arena. Please regroup to join.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('722', 'Your group has members not in your arena team. Please regroup to join.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('723', 'Your group does not have enough players to join this match.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('724', 'The Gold Team wins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('725', 'The Green Team wins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('726', 'There aren\'t enough players in this battleground. It will end soon unless some more players join to balance the fight.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('727', 'Your group has an offline member. Please remove him before joining.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('728', 'Your group has players from the opposing faction. You can\'t join the battleground as a group.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('729', 'Your group has players from different battleground brakets. You can\'t join as group.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('730', 'Someone in your party is already in this battleground queue. (S)he must leave it before joining as group.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('731', 'Someone in your party is Deserter. You can\'t join as group.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('732', 'Someone in your party is already in three battleground queues. You cannot join as group.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('733', 'You cannot teleport to a battleground or arena map.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('734', 'You cannot summon players to a battleground or arena map.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('735', 'You must be in GM mode to teleport to a player in a battleground.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('736', 'You cannot teleport to a battleground from another battleground. Please leave the current battleground first.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('173', 'You changed runic power of %s to %i/%i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('174', '%s changed your runic power to %i/%i.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1109', '%d - %s %s %s %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1122', '(%u/%u +perm %u +temp %u)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('737', 'Arenas are set to 1v1 for debugging. So, don\'t join as group.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('738', 'Arenas are set to normal playercount.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('739', 'Battlegrounds are set to 1v0 for debugging.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('740', 'Battlegrounds are set to normal playercount.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('741', 'Flushing Arena points based on team ratings, this may take a few minutes. Please stand by...', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('742', 'Distributing arena points to players...', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('743', 'Finished setting arena points for online players.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('744', 'Modifying played count, arena points etc. for loaded arena teams, sending updated stats to online players...', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('745', 'Modification done.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('746', 'Done flushing Arena points.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('810', '|Hplayer:$N|h[$N]|h has earned the achievement $a!', null, null, '|Hplayer:$N|h[$N]|h hat den Erfolg errungen $a!', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('750', 'Following BattleGrounds found:\n%s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('751', 'Not enough players. This game will close in %u seconds.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('753', 'The battle for Warsong Gulch begins in 2 minutes.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('754', 'The battle for Arathi Basin begins in 2 minutes.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('755', 'The battle for Eye of the Storm begins in 2 minutes.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('811', 'Guild Master', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('812', 'Officer', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('813', 'Veteran', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('814', 'Member', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('815', 'Initiate', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('175', 'Liquid level: %f, ground: %f, type: %d, status: %d', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('681', 'The Alliance has lost control of the Fel Reaver Ruins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('682', 'The Horde has lost control of the Fel Reaver Ruins!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('683', '%s has taken the flag!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('684', 'The Alliance have captured the flag!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('685', 'The Horde have captured the flag!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('686', 'The flag has been dropped.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('687', 'The flag has been reset.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('524', 'Selected object:\n|cffffffff|Hgameobject:%d|h[%s]|h|r GUID: %u ID: %u\nX: %f Y: %f Z: %f MapId: %u\nOrientation: %f', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1123', 'Not pet found', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1124', 'Wrong pet type', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1125', 'Your pet learned all talents', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1126', 'Your pet talents have been reset.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1127', 'Talents of %s\'s pet reset.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1011', '|<Error>        | %20s |<Error>          |<Er>| <Error>   |', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1012', '===========================================================================', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1013', '|%15s| %20s | %15s |%4d| %9d |', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1014', 'No online players.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1200', 'You try to view cinemitic %u but it doesn\'t exist.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1201', 'You try to view movie %u but it doesn\'t exist.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('59', 'Using creature EventAI: %s', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9012', 'The Alliance lost Broken Hill!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9013', 'The Horde has taken the West Beacon!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9014', 'The Alliance has taken the West Beacon!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9015', 'The Horde has taken the East Beacon!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9016', 'The Alliance has taken the East Beacon!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9017', 'The Horde has captured the Twin Spire Graveyard!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9018', 'The Alliance has captured the Twin Spire Graveyard!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9019', 'The Horde lost the West Beacon!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9020', 'The Alliance lost the West Beacon!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9021', 'The Horde lost the East Beacon!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9022', 'The Alliance lost the East Beacon!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9023', 'The Horde lost the Twin Spire Graveyard!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9024', 'The Alliance lost the Twin Spire Graveyard!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9025', 'The Horde has captured Halaa!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9026', 'The Alliance has captured Halaa!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9027', 'The Horde lost Halaa!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9028', 'The Alliance lost Halaa!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9029', 'The Horde has taken a Spirit Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9030', 'The Alliance has taken a Spirit Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9031', 'The Horde lost a Spirit Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9032', 'The Alliance lost a Spirit Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9033', 'The Horde has taken the Northpass Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9034', 'The Alliance has taken the Northpass Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9035', 'The Horde has taken the Eastwall Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9036', 'The Alliance has taken the Eastwall Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9037', 'The Horde has taken the Crown Guard Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9038', 'The Alliance has taken the Crown Guard Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9039', 'The Horde has taken the Plaguewood Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9040', 'The Alliance has taken the Plaguewood Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('790', 'The Stormpike General is Dead!', null, null, 'Der General der Horde ist tot!', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('788', 'The Horde Team is running out of reinforcements!', null, null, 'Die Horde hat nurnoch wenige VerstÃ¤rkungspunkte', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('789', 'The Frostwolf General is Dead!', null, null, 'Der General der Allianz ist tot!', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('786', 'The battle for Alterac Valley has begun!', null, null, 'Der Kampf um das Alteractal hat begonnen!', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('787', 'The Alliance Team is running out of reinforcements!', null, null, 'Die Allianz hat nurnoch wenige VerstÃ¤rkungspunkte', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('785', '30 seconds until the battle for Alterac Valley begins. Prepare yourselves!', null, null, 'Der Kampf um das Alteractal beginnt in 30 Sekunden.', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('784', '1 minute until the battle for Alterac Valley begins.', null, null, 'Der Kampf um das Alteractal beginnt in 1 Minute.', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('783', '2 minutes until the battle for Alterac Valley begins.', null, null, 'Der Kampf um das Alteractal beginnt in 2 Minuten.', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('782', 'Frostwolf Relief Hut', null, null, 'Die HeilerhÃ¼tte der FrostwÃ¶lfe', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('781', 'West Frostwolf Tower', null, null, 'Der westliche Frostwolfturm', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('780', 'East Frostwolf Tower', null, null, 'Der Ã¶stliche Frostwolfturm', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('779', 'Frostwolf Graveyard', null, null, 'Der Friedhof der FrostwÃ¶lfe', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('778', 'Tower Point', null, null, 'Die Turmstellung', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('777', 'Iceblood Graveyard', null, null, 'Der Eisblutfriedhof', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('776', 'Iceblood Tower', null, null, 'Der Eisblutturm', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('775', 'Snowfall Graveyard', null, null, 'Der Schneewehenfriedhof', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('774', 'Stonehearth Bunker', null, null, 'Der Steinbruchbunker', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('773', 'Stonehearth Graveyard', null, null, 'Der Steinbruchfriedhof', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('772', 'Icewing Bunker', null, null, 'Der Eisschwingenbunker', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('771', 'Stormpike Graveyard', null, null, 'Der Friedhof der Sturmlanzen', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('770', 'Dun Baldar North Bunker', null, null, 'Der Nordbunker von Dun Baldar', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('768', 'Stormpike Aid Station', null, null, 'Das Lazarett der Sturmlanzen', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('769', 'Dun Baldar South Bunker', null, null, 'Der SÃ¼dbunker von Dun Baldar', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('766', 'Irondeep Mine', null, null, 'Eisenschachtmine', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('767', 'Coldtooth Mine', null, null, 'EisbeiÃŸermine', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('765', 'The %s has taken the %s! Its supplies will now be used for reinforcements!', null, null, 'Die %s hat die %s eingenommen! Die dort befindlichen VorrÃ¤te werden zur VerstÃ¤rkung eingesetzt!', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('763', 'The %s was taken by the %s!', null, null, '%s wurde von der %s erobert!', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('764', 'The %s is under attack! If left unchecked, the %s will capture it!', null, null, '%s wird angegriffen! Wenn er unbewacht bleibt, wird die %s ihn erobern!', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('761', 'The %s was taken by the %s!', null, null, '%s wurde von der %s erobert!', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('762', 'The %s was taken by the %s!', null, null, '%s wurde von der %s erobert!', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('760', 'The %s is under attack! If left unchecked, the %s will destroy it!', null, null, '%s wird angegriffen! Wenn er unbewacht bleibt, wird die %s ihn zerstÃ¶ren!', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('759', '%s was destroyed by the %s!', null, null, '%s wurde von der %s zerstÃ¶rt!', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('757', 'Alliance', null, null, 'Allianz', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('758', 'Horde', null, null, 'Horde', null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('2000', '|cffffff00[|c1f40af20Announce by|r |cffff0000%s|cffffff00]:|r %s|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9011', 'The Horde lost Broken Hill!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9010', 'The Alliance lost The Stadium!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9009', 'The Horde lost The Stadium!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9008', 'The Alliance lost The Overlook!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9007', 'The Horde lost The Overlook!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9006', 'The Alliance has taken Broken Hill!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9005', 'The Horde has taken Broken Hill!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9004', 'The Alliance has taken The Stadium!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('60', '|c1f40af20 <Mod>|cffff0000[%s]|c1f40af20:|cffffff00 %s|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('61', '|c1f40af20 <GM>|cffff0000[%s]|c1f40af20:|cffffff00 %s|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('62', '|c1f40af20 <Admin>|cffff0000[%s]|c1f40af20:|cffffff00 %s|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('63', '|cffffff00[|cFFFF0000System:|r |cffffff00]:|r %s|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1202', '|cffffcc00[Server]: |cff00ff00%s|r', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9041', 'The Horde lost the Northpass Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9042', 'The Alliance lost the Northpass Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9043', 'The Horde lost the Eastwall Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9044', 'The Alliance lost the Eastwall Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9045', 'The Horde lost the Crown Guard Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9046', 'The Alliance lost the Crown Guard Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9047', 'The Horde lost the Plaguewood Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9048', 'The Alliance lost the Plaguewood Tower!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9003', 'The Horde has taken The Stadium!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9002', 'The Alliance has taken The Overlook!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9001', 'The Horde has taken The Overlook!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('749', 'No BattleGround found.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('748', '%s ended with the winner %s.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('347', 'TaxiNode ID %u not found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('466', 'No taxinodes found!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1128', '%d - |cffffffff|Htaxinode:%u|h[%s %s]|h|r (Map:%u X:%f Y:%f Z:%f)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('1129', '%d - %s %s (Map:%u X:%f Y:%f Z:%f)', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('747', '%s traveled %u seconds into the future.', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9049', 'The Horde has collected 200 silithyst!', null, null, null, null, null, null, null, null);
INSERT INTO `mangos_string` VALUES ('9050', 'The Alliance has collected 200 silithyst!', null, null, null, null, null, null, null, null);
